/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyConfidentialityRouteImport } from './routes/privacy-confidentiality'
import { Route as QualityStandardsRouteImport } from './routes/quality-standards'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as UploadPrescriptionRouteImport } from './routes/upload-prescription'
import { Route as CancerPathologySpecialtyIdRouteImport } from './routes/cancer-pathology_.$specialtyId'
import { Route as PackagesPackageIdRouteImport } from './routes/packages_.$packageId'
import { Route as ServicesServiceIdRouteImport } from './routes/services_.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyConfidentialityRoute = PrivacyConfidentialityRouteImport.update({
  id: '/privacy-confidentiality',
  path: '/privacy-confidentiality',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityStandardsRoute = QualityStandardsRouteImport.update({
  id: '/quality-standards',
  path: '/quality-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadPrescriptionRoute = UploadPrescriptionRouteImport.update({
  id: '/upload-prescription',
  path: '/upload-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const CancerPathologySpecialtyIdRoute =
  CancerPathologySpecialtyIdRouteImport.update({
    id: '/cancer-pathology_/$specialtyId',
    path: '/cancer-pathology/$specialtyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackagesPackageIdRoute = PackagesPackageIdRouteImport.update({
  id: '/packages_/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services_/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-confidentiality': typeof PrivacyConfidentialityRoute
  '/quality-standards': typeof QualityStandardsRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/cancer-pathology/$specialtyId': typeof CancerPathologySpecialtyIdRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-confidentiality': typeof PrivacyConfidentialityRoute
  '/quality-standards': typeof QualityStandardsRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/cancer-pathology/$specialtyId': typeof CancerPathologySpecialtyIdRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/privacy-confidentiality': typeof PrivacyConfidentialityRoute
  '/quality-standards': typeof QualityStandardsRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/cancer-pathology_/$specialtyId': typeof CancerPathologySpecialtyIdRoute
  '/packages_/$packageId': typeof PackagesPackageIdRoute
  '/services_/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/packages'
    | '/privacy-confidentiality'
    | '/quality-standards'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/cancer-pathology/$specialtyId'
    | '/packages/$packageId'
    | '/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/packages'
    | '/privacy-confidentiality'
    | '/quality-standards'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/cancer-pathology/$specialtyId'
    | '/packages/$packageId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/confirmation'
    | '/contact'
    | '/packages'
    | '/privacy-confidentiality'
    | '/quality-standards'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/cancer-pathology_/$specialtyId'
    | '/packages_/$packageId'
    | '/services_/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyConfidentialityRoute: typeof PrivacyConfidentialityRoute
  QualityStandardsRoute: typeof QualityStandardsRoute
  SecondOpinionRoute: typeof SecondOpinionRoute
  ServicesRoute: typeof ServicesRoute
  TestsRoute: typeof TestsRoute
  UploadPrescriptionRoute: typeof UploadPrescriptionRoute
  CancerPathologySpecialtyIdRoute: typeof CancerPathologySpecialtyIdRoute
  PackagesPackageIdRoute: typeof PackagesPackageIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-confidentiality': {
      id: '/privacy-confidentiality'
      path: '/privacy-confidentiality'
      fullPath: '/privacy-confidentiality'
      preLoaderRoute: typeof PrivacyConfidentialityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-standards': {
      id: '/quality-standards'
      path: '/quality-standards'
      fullPath: '/quality-standards'
      preLoaderRoute: typeof QualityStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-prescription': {
      id: '/upload-prescription'
      path: '/upload-prescription'
      fullPath: '/upload-prescription'
      preLoaderRoute: typeof UploadPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancer-pathology_/$specialtyId': {
      id: '/cancer-pathology_/$specialtyId'
      path: '/cancer-pathology/$specialtyId'
      fullPath: '/cancer-pathology/$specialtyId'
      preLoaderRoute: typeof CancerPathologySpecialtyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages_/$packageId': {
      id: '/packages_/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof PackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$serviceId': {
      id: '/services_/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  PrivacyConfidentialityRoute: PrivacyConfidentialityRoute,
  QualityStandardsRoute: QualityStandardsRoute,
  SecondOpinionRoute: SecondOpinionRoute,
  ServicesRoute: ServicesRoute,
  TestsRoute: TestsRoute,
  UploadPrescriptionRoute: UploadPrescriptionRoute,
  CancerPathologySpecialtyIdRoute: CancerPathologySpecialtyIdRoute,
  PackagesPackageIdRoute: PackagesPackageIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
