/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as UploadPrescriptionRouteImport } from './routes/upload-prescription'
import { Route as ServicesServiceIdRouteImport } from './routes/services_.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadPrescriptionRoute = UploadPrescriptionRouteImport.update({
  id: '/upload-prescription',
  path: '/upload-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services_/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/tests': typeof TestsRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
  '/services_/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy-policy'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy-policy'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy-policy'
    | '/second-opinion'
    | '/services'
    | '/tests'
    | '/upload-prescription'
    | '/services_/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SecondOpinionRoute: typeof SecondOpinionRoute
  ServicesRoute: typeof ServicesRoute
  TestsRoute: typeof TestsRoute
  UploadPrescriptionRoute: typeof UploadPrescriptionRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-prescription': {
      id: '/upload-prescription'
      path: '/upload-prescription'
      fullPath: '/upload-prescription'
      preLoaderRoute: typeof UploadPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$serviceId': {
      id: '/services_/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SecondOpinionRoute: SecondOpinionRoute,
  ServicesRoute: ServicesRoute,
  TestsRoute: TestsRoute,
  UploadPrescriptionRoute: UploadPrescriptionRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
